export const companies = [
  {
    id: 23,
    code: "alfa",
    name: "АльфаСтрахование",
    url: "http://www.alfastrah.ru/",
    colorHexCode: "#ef3124",
    touristMaxAgeInYears: 100,
    isInsurerInRussian: true,
  },
  {
    id: 29,
    code: "tinkoff",
    name: "Тинькофф Страхование",
    url: "https://www.tinkoffinsurance.ru/",
    colorHexCode: "#ffdd2e",
    touristMaxAgeInYears: 74,
    isInsurerInRussian: true,
  },
  {
    id: 35,
    code: "ingos",
    name: "Ингосстрах",
    url: "http://www.ingos.ru/",
    colorHexCode: "#36415a",
    touristMaxAgeInYears: 99,
    isInsurerInRussian: false,
  },
  {
    id: 43,
    code: "sovcombank",
    name: "Совкомбанк Страхование",
    url: "https://sovcomins.ru/",
    colorHexCode: "#616265",
    touristMaxAgeInYears: 100,
    isInsurerInRussian: false,
  },
  {
    id: 47,
    code: "renins",
    name: "Ренессанс",
    url: "http://www.renins.com/",
    colorHexCode: "#6c3d7c",
    touristMaxAgeInYears: 64,
    isInsurerInRussian: false,
  },
  {
    id: 48,
    code: "reso",
    name: "РЕСО Гарантия",
    url: "http://www.reso.ru/",
    colorHexCode: "#2a7849",
    touristMaxAgeInYears: 85,
    isInsurerInRussian: false,
  },
  {
    id: 51,
    code: "soglasie",
    name: "Согласие",
    url: "http://www.soglasie.ru/",
    colorHexCode: "#e87932",
    touristMaxAgeInYears: 80,
    isInsurerInRussian: true,
  },
  {
    id: 52,
    code: "rstandart",
    name: "Русский Стандарт",
    url: "http://www.rsins.ru/",
    colorHexCode: "#8f0a0a",
    touristMaxAgeInYears: 100,
    isInsurerInRussian: true,
  },
  {
    id: 57,
    code: "absolut",
    name: "Абсолют Страхование",
    url: "https://www.absolutins.ru/",
    colorHexCode: "#ee2d23",
    touristMaxAgeInYears: 80,
    isInsurerInRussian: false,
  },
  {
    id: 59,
    code: "sberbank",
    name: "СберСтрахование",
    url: "http://www.sberbank.ru",
    colorHexCode: "#9acd32",
    touristMaxAgeInYears: 80,
  },
  {
    id: 62,
    code: "energogarant",
    name: "ЭНЕРГОГАРАНТ",
    url: "https://www.energogarant.ru/",
    colorHexCode: "#EE2121",
    touristMaxAgeInYears: 100,
    isInsurerInRussian: false,
  },
];

export const mockTravels = [
  {
    productId: 80,
    companyId: 43,
    price: 29.11,
    priceRub: 2365.9,
    assistances: [
      {
        code: "class",
        name: "Class Assistance",
      },
    ],
    matchRating: 0.8882,
    matchDetails: {
      totalServices: 23,
      additionalServices: 20,
      missingServices: 0,
      matchingServices: 3,
      higherSumms: 0,
      lowerSumms: 0,
      matchingSumms: 1,
      expertRaiting: 0,
      isLimited: 0,
      priceRating: 0.0106,
      payoutRating: 0.01065,
    },
    serviceProduct: {
      abroad: 0,
      abroadTransportation: 1,
      accident: 0,
      allergyArresting: 1,
      ambulatoryCare: 1,
      auto: 0,
      aviaCargo: 0,
      childrenReturn: 1,
      chronicArresting: 2000,
      civilLiability: 0,
      covid: 1,
      deathRepatriation: 1,
      delayCargo: 0,
      denge: 1,
      divingChamber: 0,
      doctorCall: 1,
      doctorTransportation: 1,
      drugRefund: 1,
      education: 0,
      foreign: 1,
      hospitalTreatment: 1,
      insuredEscortReturn: 1,
      insuredLiving: 1,
      insuredReturn: 1,
      medicine: 50000,
      multipolicy: 0,
      office: 0,
      pcr: 0,
      phoneRefund: 1,
      pregnancy: 0,
      relativeIllReturn: 1,
      searchActivities: 5000,
      sunburnAssistance: 1,
      thirdPartyTransportation: 1,
      urgentStomatology: 1,
      work: 0,
    },
    info: {
      medicine: [
        {
          type: "franchise",
          value: "30",
        },
      ],
      searchActivities: [
        {
          type: "limitation",
          value:
            "Расходы на транспортировку / эвакуацию Застрахованного вертолетным транспортом возмещаются в пределах 5000 у.е.",
        },
      ],
    },
  },
  {
    productId: 38,
    companyId: 29,
    price: 33.71,
    priceRub: 2740,
    assistances: [
      {
        code: "eurasia",
        name: "Eurasia Assistance",
      },
      {
        code: "best",
        name: " Best Service",
      },
    ],
    matchRating: 0.7581,
    matchDetails: {
      totalServices: 25,
      additionalServices: 22,
      missingServices: 0,
      matchingServices: 3,
      higherSumms: 0,
      lowerSumms: 0,
      matchingSumms: 1,
      expertRaiting: 0,
      isLimited: 0,
      priceRating: 0.0069,
      payoutRating: 0.01065,
    },
    serviceProduct: {
      abroad: 0,
      abroadTransportation: 1,
      accident: 0,
      alcoholAssistance: 0,
      allergyArresting: 1,
      ambulatoryCare: 1,
      aviaCargo: 0,
      childrenReturn: 1,
      chronicArresting: 1,
      civilLiability: 0,
      covid: 1,
      deathRepatriation: 1,
      denge: 1,
      disasterAssistance: 1,
      doctorCall: 1,
      doctorTransportation: 1,
      document: 1000,
      drugRefund: 1,
      education: 0,
      foreign: 1,
      hospitalTreatment: 1,
      hotelCargo: 0,
      insuredEscortReturn: 0,
      insuredLiving: 1,
      insuredReturn: 1,
      legal: 1000,
      medicine: 50000,
      multipolicy: 0,
      office: 0,
      pcr: 0,
      phoneRefund: 1,
      relativeIllReturn: 0,
      sunburnAssistance: 1,
      terrorAssistance: 1,
      thirdPartyTransportation: 1,
      urgentStomatology: 1,
    },
    info: null,
  },
  {
    productId: 9,
    companyId: 23,
    price: 34.75,
    priceRub: 2824.29,
    assistances: [
      {
        code: "balt",
        name: "Balt Assistance",
      },
    ],
    matchRating: 0.731,
    matchDetails: {
      totalServices: 23,
      additionalServices: 20,
      missingServices: 0,
      matchingServices: 3,
      higherSumms: 0,
      lowerSumms: 0,
      matchingSumms: 1,
      expertRaiting: 0,
      isLimited: 0,
      priceRating: 0.0061,
      payoutRating: 0.01065,
    },
    serviceProduct: {
      abroad: 0,
      abroadTransportation: 50000,
      accident: 0,
      allergyArresting: 1,
      ambulatoryCare: 50000,
      aviaCargo: 0,
      childrenReturn: 2000,
      chronicArresting: 1,
      civilLiability: 0,
      covid: 1,
      deathRepatriation: 10000,
      denge: 1,
      disasterAssistance: 1,
      divingChamber: 0,
      doctorCall: 50000,
      doctorTransportation: 50000,
      document: 300,
      drugRefund: 50000,
      education: 0,
      foreign: 1,
      hospitalTreatment: 50000,
      insuredReturn: 2000,
      legal: 5000,
      medicine: 50000,
      observation: 0,
      office: 0,
      pcr: 0,
      phoneRefund: 100,
      regularDelay: 1,
      relativeIllReturn: 2000,
      searchActivities: 0,
      thirdPartyTransportation: 2000,
      urgentStomatology: 200,
      work: 0,
    },
    info: null,
  },
];
