export const countriesGroup = ["all-world", "shengen"] as const;

export const countries = [
  "albania",
  "argentina",
  "armenia",
  "australia",
  "austria",
  "azerbaijan",
  "bahrain",
  "belarus",
  "belgium",
  "china",
  "france",
  "georgia",
  "germany",
  "greece",
  "india",
  "indonesia",
  "iran",
  "ireland",
  "usa",
  "italy",
  "japan",
  "kazakhstan",
  "kyrgyzstan",
  "latvia",
  "lithuania",
  "malaysia",
  "mexico",
  "moldova",
  "montenegro",
  "netherlands",
  "new-zealand",
  "norway",
];
